name: Advent of Code 2024 CI
on: [push]
jobs:
    test:
        runs-on: ubuntu-latest
        steps:
            - name: Check out repository code
              uses: actions/checkout@v4
            - name: set up node/typescript
              uses: actions/setup-node@v4
              with:
                node-version: 20
            - name: Install dependencies
              run: npm install
            - name: Run lint
              run: npm run lint
            - name: Run tests
              run: npm test
            - name: Generate coverage report
              uses: ArtiomTr/jest-coverage-report-action@v2
            - name: Upload test report
              uses: actions/upload-artifact@v4
              if: success() || failure()
              with:
                  name: test-results
                  path: reports/report.xml
            - name: Publish test report
              uses: dorny/test-reporter@v1
              with:
                  artifacts: test-results
                  name: Jest Tests
                  path: '*.xml'
                  reporter: jest-junit